version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/shop
      - JWT_SECRET=your-secret-key
    depends_on:
      db:
        condition: service_healthy
  
  tests:
    build: .
    entrypoint: [""]
    command: sh -c "python -m app.init_db && pytest --maxfail=1 --disable-warnings -v -s"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/shop
      - JWT_SECRET=your-secret-key
    depends_on:
      db:
        condition: service_healthy
  
  e2e-tests:
    build: .
    entrypoint: [""]
    command: sh -c "sleep 15 && python tests/e2e_tests.py"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/shop
      - JWT_SECRET=your-secret-key
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: